name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e
            
            # Define paths
            APP_DIR="/var/www/hvac-chatbot"
            REPO_URL="https://github.com/dutchiono/hvac-ai-secretary.git"
            
            echo "ðŸš€ Starting deployment..."
            
            # Initial deployment or update
            if [ -d "$APP_DIR" ]; then
              echo "ðŸ“¦ Updating existing application..."
              cd $APP_DIR
              git pull origin main
            else
              echo "ðŸ“¦ Initial deployment - cloning repository..."
              git clone $REPO_URL $APP_DIR
              cd $APP_DIR
            fi
            
            # Install/update dependencies
            echo "ðŸ“¥ Installing dependencies..."
            npm install --production
            
            # Set up Nginx (only if not already configured)
            if [ ! -f "/etc/nginx/sites-available/hvac.bushleague.xyz" ]; then
              echo "ðŸŒ Setting up Nginx..."
              apt-get update && apt-get install -y nginx
              cat > /etc/nginx/sites-available/hvac.bushleague.xyz << 'EOF'
            server {
                listen 80;
                server_name hvac.bushleague.xyz;

                location / {
                    proxy_pass http://localhost:3145;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host $host;
                    proxy_cache_bypass $http_upgrade;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
            }
            EOF
              ln -sf /etc/nginx/sites-available/hvac.bushleague.xyz /etc/nginx/sites-enabled/
              nginx -t && systemctl reload nginx
            fi
            
            # Set up systemd service (only if not already configured)
            if [ ! -f "/etc/systemd/system/hvac-chatbot.service" ]; then
              echo "âš™ï¸ Setting up systemd service..."
              cat > /etc/systemd/system/hvac-chatbot.service << 'EOF'
            [Unit]
            Description=HVAC AI Chatbot Service
            After=network.target

            [Service]
            Type=simple
            User=www-data
            WorkingDirectory=/var/www/hvac-chatbot
            ExecStart=/usr/bin/node server.js
            Restart=always
            RestartSec=10
            StandardOutput=syslog
            StandardError=syslog
            SyslogIdentifier=hvac-chatbot
            Environment=NODE_ENV=production
            Environment=PORT=3145

            [Install]
            WantedBy=multi-user.target
            EOF
              systemctl daemon-reload
              systemctl enable hvac-chatbot
            fi
            
            # Set up environment file (only if not exists)
            if [ ! -f "$APP_DIR/.env" ]; then
              echo "ðŸ“ Creating .env file..."
              cat > $APP_DIR/.env << 'EOF'
            PORT=3145
            NODE_ENV=production
            TWILIO_ACCOUNT_SID=your_twilio_account_sid_here
            TWILIO_AUTH_TOKEN=your_twilio_auth_token_here
            TWILIO_PHONE_NUMBER=your_twilio_phone_number_here
            GROQ_API_KEY=your_groq_api_key_here
            EOF
              echo "âš ï¸ REMINDER: Add API keys to $APP_DIR/.env"
            fi
            
            # Set permissions
            echo "ðŸ”’ Setting permissions..."
            chown -R www-data:www-data $APP_DIR
            
            # Restart service
            echo "ðŸ”„ Restarting service..."
            systemctl restart hvac-chatbot
            
            # Set up SSL (only if certificate doesn't exist)
            if [ ! -f "/etc/letsencrypt/live/hvac.bushleague.xyz/fullchain.pem" ]; then
              echo "ðŸ” Setting up SSL with Certbot..."
              apt-get install -y certbot python3-certbot-nginx
              certbot --nginx -d hvac.bushleague.xyz --non-interactive --agree-tos --email dutchiono@gmail.com || echo "âš ï¸ Certbot failed, continuing without SSL"
            fi
            
            # Show status
            echo "âœ… Deployment complete!"
            systemctl status hvac-chatbot --no-pager
            
            echo ""
            echo "ðŸŒ Site: https://hvac.bushleague.xyz"
            echo "ðŸ“‹ Logs: journalctl -u hvac-chatbot -f"