name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e

            APP_DIR="/var/www/hvac-ai-secretary"
            REPO_URL="https://github.com/dutchiono/hvac-ai-secretary.git"

            echo "Starting deployment..."

            if [ -d "$APP_DIR/.git" ]; then
              echo "Pulling latest changes..."
              cd $APP_DIR
              git pull origin main
            else
              echo "Initial clone..."
              git clone $REPO_URL $APP_DIR
              cd $APP_DIR
            fi

            echo "Installing dependencies..."
            npm install --omit=dev

            echo "Creating .env file with secrets..."
            cat > .env << 'ENVEOF'
PORT=3145
NODE_ENV=production
GMAIL_USER=${{ secrets.GMAIL_USER }}
GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}
NOTIFICATION_EMAIL=${{ secrets.NOTIFICATION_EMAIL }}
GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}
ENVEOF

            echo "Ensuring data directory exists..."
            mkdir -p $APP_DIR/data

            echo "Restarting service..."
            sudo systemctl restart hvac-ai-secretary

            echo "Deployment complete!"
            sudo systemctl status hvac-ai-secretary --no-pager
