name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e
            
            APP_DIR="/var/www/hvac-ai-secretary"
            REPO_URL="https://github.com/dutchiono/hvac-ai-secretary.git"
            
            echo "ðŸš€ Starting deployment..."
            
            if [ -d "$APP_DIR" ]; then
              echo "ðŸ“¦ Updating existing application..."
              cd $APP_DIR
              git pull origin main
            else
              echo "ðŸ“¦ Initial deployment - cloning repository..."
              sudo mkdir -p $APP_DIR
              sudo chown -R $USER:$USER $APP_DIR
              git clone $REPO_URL $APP_DIR
              cd $APP_DIR
            fi
            
            echo "ðŸ“¥ Installing dependencies..."
            npm install --production
            
            if [ ! -f "/etc/nginx/sites-available/hvac.bushleague.xyz" ]; then
              echo "ðŸŒ Setting up Nginx..."
              sudo apt-get update && sudo apt-get install -y nginx
              sudo tee /etc/nginx/sites-available/hvac.bushleague.xyz > /dev/null <<EOF
            server {
                listen 80;
                server_name hvac.bushleague.xyz;
                location / {
                    proxy_pass http://localhost:3145;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade \$http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host \$host;
                    proxy_cache_bypass \$http_upgrade;
                }
            }
            EOF
              sudo ln -sf /etc/nginx/sites-available/hvac.bushleague.xyz /etc/nginx/sites-enabled/
              sudo nginx -t && sudo systemctl reload nginx
            fi
            
            if [ ! -f "/etc/systemd/system/hvac-chatbot.service" ]; then
              echo "âš™ï¸ Setting up systemd service..."
              sudo tee /etc/systemd/system/hvac-chatbot.service > /dev/null <<EOF
            [Unit]
            Description=HVAC AI Chatbot Service
            After=network.target
            [Service]
            Type=simple
            User=www-data
            WorkingDirectory=/var/www/hvac-ai-secretary
            ExecStart=/usr/bin/node server.js
            Restart=always
            RestartSec=10
            Environment=NODE_ENV=production
            Environment=PORT=3145
            [Install]
            WantedBy=multi-user.target
            EOF
              sudo systemctl daemon-reload
              sudo systemctl enable hvac-chatbot
            fi
            
            touch $APP_DIR/.env
            
            echo "ðŸ”’ Setting permissions..."
            sudo chown -R www-data:www-data $APP_DIR
            
            echo "ðŸ”„ Restarting service..."
            sudo systemctl restart hvac-chatbot
            
            echo "âœ… Deployment complete!"
            sudo systemctl status hvac-chatbot --no-pager