name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: GMAIL_USER,GMAIL_APP_PASSWORD,NOTIFICATION_EMAIL,GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,GOOGLE_REDIRECT_URI
          script: |
            set -e

            APP_DIR="/var/www/hvac-ai-secretary"
            REPO_URL="https://github.com/iono-such-things/hvac-ai-secretary.git"

            echo "Starting deployment..."

            if [ -d "$APP_DIR/.git" ]; then
              echo "Pulling latest changes..."
              cd $APP_DIR
              git fetch origin main
              git reset --hard origin/main
            else
              echo "Initial clone..."
              git clone $REPO_URL $APP_DIR
              cd $APP_DIR
            fi

            cd $APP_DIR

            echo "Clearing root-owned node_modules..."
            sudo rm -rf node_modules

            echo "Installing dependencies..."
            npm install --omit=dev

            echo "Writing .env from secrets..."
            cat > .env << EOF
PORT=3145
NODE_ENV=production
GMAIL_USER=${GMAIL_USER}
GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
NOTIFICATION_EMAIL=${NOTIFICATION_EMAIL}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
EOF

            echo "Ensuring data directory exists..."
            mkdir -p $APP_DIR/data

            echo "Restarting service..."
            sudo systemctl restart hvac-ai-secretary

            echo "Deployment complete!"
            sudo systemctl status hvac-ai-secretary --no-pager
